import { Inter } from 'next/font/google';
import '../app/styles/globals.css';
import Header from '../components/Header';
import Footer from '../components/Footer';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'فیلم کده',
  description: 'Generated by create next app',
};

export default function RootLayout({ children, showNavbarAndFooter }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {showNavbarAndFooter && <Header />}
        <main>{children}</main>
        {showNavbarAndFooter && <Footer />}
      </body>
    </html>
  );
}
